import type { BudgetRequest } from "../types";

export const MOCK_BUDGET_REQUESTS: BudgetRequest[] = [
  {
    id: "DSB-2025-001",
    projectId: "PRP-2024-001",
    projectTitle: "Deep Learning for Early Malaria Detection in Sub-Saharan Africa",
    pi: "Dr. L. Vance",
    piAvatar: "LV",
    piColor: "bg-purple-100 text-purple-700",
    dept: "Computer Science",
    totalBudget: 92000,
    mode: "Phased",
    bankRoutingInfo: "College of Science — Ledger A-204 · Ref: PROJ-LV-001",
    pgOfficerNote:
      "Approved for phased release. Phase 1 is initial equipment. Clearance required before each subsequent phase.",
    activePhasIndex: 1,
    phases: [
      {
        phase: 1,
        label: "Initial Equipment & Setup",
        amount: 45000,
        status: "Paid",
        clearanceFileName: null,
        submittedAt: "Mar 14, 2025",
        actedAt: "Mar 16, 2025",
        transactionId: "TXN-ETB-002341",
        approvedAmount: 45000,
        financeComment: null,
      },
      {
        phase: 2,
        label: "Data Collection & Labeling",
        amount: 25000,
        status: "Pending",
        clearanceFileName: "clearance_phase1_lv.pdf",
        submittedAt: "Apr 2, 2025",
        actedAt: null,
        transactionId: null,
        approvedAmount: null,
        financeComment: null,
      },
      {
        phase: 3,
        label: "Travel & Dissemination",
        amount: 22000,
        status: "Pending",
        clearanceFileName: null,
        submittedAt: null,
        actedAt: null,
        transactionId: null,
        approvedAmount: null,
        financeComment: null,
      },
    ],
  },
  {
    id: "DSB-2025-002",
    projectId: "PRP-2024-002",
    projectTitle: "Hybrid Solar-Wind Micro-Grid Systems for Rural Electrification",
    pi: "Prof. E. Stark",
    piAvatar: "ES",
    piColor: "bg-emerald-100 text-emerald-700",
    dept: "Engineering",
    totalBudget: 185000,
    mode: "All-at-once",
    bankRoutingInfo: "Engineering Faculty Main Account · Ref: PROJ-ES-002",
    pgOfficerNote: "Full budget approved for single release. No phasing required.",
    activePhasIndex: 0,
    phases: [
      {
        phase: 1,
        label: "Full Project Budget",
        amount: 185000,
        status: "Pending",
        clearanceFileName: null,
        submittedAt: "Apr 1, 2025",
        actedAt: null,
        transactionId: null,
        approvedAmount: null,
        financeComment: null,
      },
    ],
  },
  {
    id: "DSB-2025-003",
    projectId: "PRP-2024-004",
    projectTitle: "Quantum-Assisted Optimization for Supply Chain Logistics",
    pi: "Dr. A. Turing",
    piAvatar: "AT",
    piColor: "bg-blue-100 text-blue-700",
    dept: "Physics",
    totalBudget: 220000,
    mode: "Phased",
    bankRoutingInfo: "Physics Dept. Research Account · Ref: PROJ-AT-004",
    pgOfficerNote:
      "Phased. Clearance of prior spend required. Substantial cloud computing costs — verify invoices carefully.",
    activePhasIndex: 1,
    phases: [
      {
        phase: 1,
        label: "Cloud Compute Access",
        amount: 120000,
        status: "Paid",
        clearanceFileName: null,
        submittedAt: "Feb 28, 2025",
        actedAt: "Mar 5, 2025",
        transactionId: "TXN-ETB-001920",
        approvedAmount: 120000,
        financeComment: null,
      },
      {
        phase: 2,
        label: "Research Stipends & Tools",
        amount: 80000,
        status: "Returned",
        clearanceFileName: "clearance_phase1_at.pdf",
        submittedAt: "Mar 28, 2025",
        actedAt: "Apr 1, 2025",
        transactionId: null,
        approvedAmount: null,
        financeComment: "Missing signature on cloud provider invoice. Please resubmit with authorized clearance.",
      },
      {
        phase: 3,
        label: "Conference Travel",
        amount: 20000,
        status: "Pending",
        clearanceFileName: null,
        submittedAt: null,
        actedAt: null,
        transactionId: null,
        approvedAmount: null,
        financeComment: null,
      },
    ],
  },
  {
    id: "DSB-2025-004",
    projectId: "PRP-2024-005",
    projectTitle: "Nanotechnology-Enhanced Drug Delivery for Cervical Cancer",
    pi: "Prof. R. Musa",
    piAvatar: "RM",
    piColor: "bg-amber-100 text-amber-700",
    dept: "Biomedical Sciences",
    totalBudget: 310000,
    mode: "Phased",
    bankRoutingInfo: "Biomedical Research Trust Fund · Ref: PROJ-RM-005",
    pgOfficerNote:
      "High-value grant. Phased release mandatory. Finance to verify all chemical procurement receipts before each release.",
    activePhasIndex: 0,
    phases: [
      {
        phase: 1,
        label: "Lipid Precursors & Lab Setup",
        amount: 110000,
        status: "Resubmitted",
        clearanceFileName: null,
        submittedAt: "Apr 3, 2025",
        actedAt: null,
        transactionId: null,
        approvedAmount: null,
        financeComment: null,
      },
      {
        phase: 2,
        label: "Cell Lines & Culture Media",
        amount: 90000,
        status: "Pending",
        clearanceFileName: null,
        submittedAt: null,
        actedAt: null,
        transactionId: null,
        approvedAmount: null,
        financeComment: null,
      },
      {
        phase: 3,
        label: "Microscopy & Assay Kits",
        amount: 110000,
        status: "Pending",
        clearanceFileName: null,
        submittedAt: null,
        actedAt: null,
        transactionId: null,
        approvedAmount: null,
        financeComment: null,
      },
    ],
  },
];
